### ISSUE TITLE
我所認為的單元測試

### ISSUE THREAD

**Issue by MilesChou** [MilesChou/todo#33]

**Comment by MilesChou** [comment]
打了兩篇，累了

https://mileschou.github.io/blog/about-unit-test/
https://mileschou.github.io/blog/about-unit-test-manager-perspective/

**Comment by yuanyu90221** [comment]
師父我想學好單元測試

**Comment by yuanyu90221** [comment]
師父 我想學習unittest

**Comment by tedmax100** [comment]
師父 我想學習unittest
